// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2dbd5940-c6d6-465b-bb77-36182d7b48dd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xcnXEaIfW",
    "aws_user_pools_web_client_id": "2gkfcbr28p636pgnv280hpf1aq"
};


export default awsmobile;
